# Mount EFS to server
- name: create data directory
  file: path=/data state=directory

- name: Mount EFS to server
  mount:
    path: /data
    src: "{{ efs_dns_name }}:/"
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
    fstype: nfs4
    state: mounted

# Install docker on CentOS
- name: Installing Docker repo
  get_url: url=https://download.docker.com/linux/centos/docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo

- name: "Installing docker-ce package"
  yum: pkg=docker-ce state=present

- name: Start docker
  service: name=docker state=started enabled=yes
