# Disable Selinux
- name: Disable SELinux
  selinux:
    state: disabled

# Mount EFS to server
- name: create data directory
  file: path=/data state=directory

- name: Sleep before mount EFS
  command: "sleep 60"

- name: Mount EFS to server
  mount:
    path: /data
    src: "{{ efs_dns_name }}:/"
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
    fstype: nfs4
    state: mounted

- name: create Prometheus database directory
  file: path=/data/prometheus/database state=directory recurse=yes mode=0777

- name: create Prometheus configure directory
  file: path=/data/prometheus/config state=directory recurse=yes

- name: Copy prometheus.yml
  copy: src=prometheus.yml dest=/data/prometheus/config/prometheus.yml

- name: create Grafana directory
  file: path=/data/grafana state=directory mode=0777

# Install docker on CentOS
- name: Installing Docker repo
  get_url: url=https://download.docker.com/linux/centos/docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo

- name: "Installing packages"
  yum: pkg={{item}} state=present
  with_items:
  - python-pip
  - docker-ce

- name: "Install docker-py"
  pip: name=docker-py state=present

- name: Start docker
  service: name=docker state=started enabled=yes

# Start Prometheus with docker
- name: Run container Prometheus
  docker_container:
    name: prometheus
    state: started
    image: prom/prometheus:latest
    volumes: /data/prometheus:/prometheus:rw
    command: ["--config.file=/prometheus/config/prometheus.yml", "--storage.tsdb.path=/prometheus/database"]
    published_ports: 0.0.0.0:9090:9090

- name: Run container Grafana
  docker_container:
    name: grafana
    state: started
    image: grafana/grafana:latest
    volumes: /data/grafana:/var/lib/grafana:rw
    published_ports: 0.0.0.0:3000:3000

- name: Run container node_exporter
  docker_container:
    name: node-exporter
    state: started
    image: prom/node-exporter:latest
    published_ports: 0.0.0.0:9100:9100
